Repository sbb-design-systems/lyne-angular, pull requests merged in 2025-03, with the labels that each got.

#27 chore: fix storybook link
  src/showcase/.storybook/preview-head.html
Labels: pr: peer review required, pr: lead review approved

#28 docs: improve documentation
  README.md
  docs/CONTRIBUTING.md
  src/showcase/.storybook/preview.ts
  src/showcase/docs/getting-started.mdx
Labels: pr: peer review approved, pr: lead review approved

#30 fix(sbb-select): correctly update state on change
  src/angular/select/select.ts
Labels: pr: peer review approved, pr: lead review approved

#32 feat(sbb-toggle): add ControlValueAccessor implementation
  src/angular/toggle/toggle/toggle.ts
Labels: pr: peer review approved, pr: lead review approved

#34 chore(sbb-form-field): fix broken story
  src/showcase/stories/angular/form-field/form-field/form-field.stories.ts
Labels: pr: peer review required, pr: lead review approved

#33 feat: upgrade lyne-elements
  angular.json
  package.json
  src/angular/calendar/calendar.ts
  src/angular/date-input/date-input.ts
  src/angular/date-input/index.ts
  src/angular/date-input/ng-package.json
  src/angular/datepicker/datepicker/datepicker.ts
  src/angular/tag/tag-group/tag-group.ts
  src/showcase/stories/angular/calendar/calendar.stories.ts
  src/showcase/stories/angular/date-input/date-input.stories.ts
  yarn.lock
Labels: pr: peer review required, pr: lead review approved

#39 feat(sbb-date-input): add Angular Forms validation
  src/angular/date-input/date-input.ts
Labels: pr: peer review approved, pr: lead review approved

#40 fix: remove output annotation to avoid duplicate events
  src/angular/alert/alert-group/alert-group.ts
  src/angular/alert/alert/alert.ts
  src/angular/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.ts
  src/angular/autocomplete-grid/autocomplete-grid/autocomplete-grid.ts
  src/angular/autocomplete/autocomplete.ts
  src/angular/calendar/calendar.ts
  src/angular/checkbox/checkbox-panel/checkbox-panel.ts
  src/angular/checkbox/checkbox/checkbox.ts
  src/angular/container/sticky-bar/sticky-bar.ts
  src/angular/date-input/date-input.ts
  src/angular/datepicker/datepicker/datepicker.ts
  src/angular/dialog/dialog-title/dialog-title.ts
  src/angular/dialog/dialog/dialog.ts
  src/angular/expansion-panel/expansion-panel-header/expansion-panel-header.ts
  src/angular/expansion-panel/expansion-panel/expansion-panel.ts
  src/angular/file-selector/file-selector-dropzone/file-selector-dropzone.ts
  src/angular/file-selector/file-selector/file-selector.ts
  src/angular/flip-card/flip-card/flip-card.ts
  src/angular/image/image.ts
  src/angular/menu/menu/menu.ts
  src/angular/navigation/navigation/navigation.ts
  src/angular/notification/notification.ts
  src/angular/option/option/option.ts
  src/angular/overlay/overlay.ts
  src/angular/paginator/compact-paginator/compact-paginator.ts
  src/angular/paginator/paginator/paginator.ts
  src/angular/popover/popover/popover.ts
  src/angular/radio-button/radio-button-group/radio-button-group.ts
  src/angular/radio-button/radio-button-panel/radio-button-panel.ts
  src/angular/radio-button/radio-button/radio-button.ts
  src/angular/select/select.ts
  src/angular/selection-expansion-panel/selection-expansion-panel.ts
  src/angular/slider/slider.ts
  src/angular/stepper/step/step.ts
  src/angular/tabs/tab-group/tab-group.ts
  src/angular/tag/tag/tag.ts
  src/angular/time-input/time-input.ts
  src/angular/toast/toast.ts
  src/angular/toggle-check/toggle-check.ts
  src/angular/toggle/toggle/toggle.ts
  tools/eslint/angular-generator-rule.ts
Labels: pr: peer review required, pr: lead review approved

#41 build: add start script
  package.json
  scripts/serve.mts
Labels: pr: peer review approved, pr: lead review approved

#37 fix: replace input with sbb-date-input in stories
  src/angular/date-input/date-input.ts
  src/showcase/stories/angular/datepicker/datepicker-next-day/datepicker-next-day.stories.ts
  src/showcase/stories/angular/datepicker/datepicker-previous-day/datepicker-previous-day.stories.ts
  src/showcase/stories/angular/datepicker/datepicker-toggle/datepicker-toggle.stories.ts
  src/showcase/stories/angular/datepicker/datepicker/datepicker.stories.ts
Labels: pr: peer review required, pr: lead review approved

#42 fix: duplicate events
  src/angular/alert/alert-group/alert-group.ts
  src/angular/alert/alert/alert.ts
  src/angular/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.ts
  src/angular/autocomplete-grid/autocomplete-grid/autocomplete-grid.ts
  src/angular/autocomplete/autocomplete.ts
  src/angular/calendar/calendar.ts
  src/angular/checkbox/checkbox-panel/checkbox-panel.ts
  src/angular/checkbox/checkbox/checkbox.ts
  src/angular/container/sticky-bar/sticky-bar.ts
  src/angular/date-input/date-input.ts
  src/angular/datepicker/datepicker/datepicker.ts
  src/angular/dialog/dialog-title/dialog-title.ts
  src/angular/dialog/dialog/dialog.ts
  src/angular/expansion-panel/expansion-panel-header/expansion-panel-header.ts
  src/angular/expansion-panel/expansion-panel/expansion-panel.ts
  src/angular/file-selector/file-selector-dropzone/file-selector-dropzone.ts
  src/angular/file-selector/file-selector/file-selector.ts
  src/angular/flip-card/flip-card/flip-card.ts
  src/angular/image/image.ts
  src/angular/menu/menu/menu.ts
  src/angular/navigation/navigation/navigation.ts
  src/angular/notification/notification.ts
  src/angular/option/option/option.ts
  src/angular/overlay/overlay.ts
  src/angular/paginator/compact-paginator/compact-paginator.ts
  src/angular/paginator/paginator/paginator.ts
  src/angular/popover/popover/popover.ts
  src/angular/radio-button/radio-button-group/radio-button-group.ts
  src/angular/radio-button/radio-button-panel/radio-button-panel.ts
  src/angular/radio-button/radio-button/radio-button.ts
  src/angular/select/select.ts
  src/angular/selection-expansion-panel/selection-expansion-panel.ts
  src/angular/slider/slider.ts
  src/angular/stepper/step/step.ts
  src/angular/tabs/tab-group/tab-group.ts
  src/angular/tag/tag/tag.ts
  src/angular/time-input/time-input.ts
  src/angular/toast/toast.ts
  src/angular/toggle-check/toggle-check.ts
  src/angular/toggle/toggle/toggle.ts
  tools/eslint/angular-generator-rule.ts
Labels: pr: peer review required

#45 fix(sbb-tag): add form support
  src/angular/tag/tag/tag.ts
Labels: pr: peer review required, pr: lead review approved

#44 fix(sbb-slider): update value correctly
  src/angular/slider/slider.ts
Labels: pr: peer review required, pr: lead review approved

#43 refactor: update angular elements
  package.json
  src/angular/date-input/date-input.ts
  src/angular/sidebar/icon-sidebar-button/icon-sidebar-button.ts
  src/angular/sidebar/icon-sidebar-button/index.ts
  src/angular/sidebar/icon-sidebar-button/ng-package.json
  src/angular/sidebar/icon-sidebar-container/icon-sidebar-container.ts
  src/angular/sidebar/icon-sidebar-container/index.ts
  src/angular/sidebar/icon-sidebar-container/ng-package.json
  src/angular/sidebar/icon-sidebar-content/icon-sidebar-content.ts
  src/angular/sidebar/icon-sidebar-content/index.ts
  src/angular/sidebar/icon-sidebar-content/ng-package.json
  src/angular/sidebar/icon-sidebar-link/icon-sidebar-link.ts
  src/angular/sidebar/icon-sidebar-link/index.ts
  src/angular/sidebar/icon-sidebar-link/ng-package.json
  src/angular/sidebar/icon-sidebar/icon-sidebar.ts
  src/angular/sidebar/icon-sidebar/index.ts
  src/angular/sidebar/icon-sidebar/ng-package.json
  src/angular/sidebar/sidebar-close-button/index.ts
  src/angular/sidebar/sidebar-close-button/ng-package.json
  src/angular/sidebar/sidebar-close-button/sidebar-close-button.ts
  src/angular/sidebar/sidebar-container/index.ts
  src/angular/sidebar/sidebar-container/ng-package.json
  src/angular/sidebar/sidebar-container/sidebar-container.ts
  src/angular/sidebar/sidebar-content/index.ts
  src/angular/sidebar/sidebar-content/ng-package.json
  src/angular/sidebar/sidebar-content/sidebar-content.ts
  src/angular/sidebar/sidebar-title/index.ts
  src/angular/sidebar/sidebar-title/ng-package.json
  src/angular/sidebar/sidebar-title/sidebar-title.ts
  src/angular/sidebar/sidebar/index.ts
  src/angular/sidebar/sidebar/ng-package.json
  src/angular/sidebar/sidebar/sidebar.ts
  src/showcase/stories/angular/sidebar/icon-sidebar-button/icon-sidebar-button.stories.ts
  src/showcase/stories/angular/sidebar/icon-sidebar-container/icon-sidebar-container.stories.ts
  src/showcase/stories/angular/sidebar/icon-sidebar-content/icon-sidebar-content.stories.ts
  src/showcase/stories/angular/sidebar/icon-sidebar-link/icon-sidebar-link.stories.ts
  src/showcase/stories/angular/sidebar/icon-sidebar/icon-sidebar.stories.ts
  src/showcase/stories/angular/sidebar/sidebar-close-button/sidebar-close-button.stories.ts
  src/showcase/stories/angular/sidebar/sidebar-container/sidebar-container.stories.ts
  src/showcase/stories/angular/sidebar/sidebar-content/sidebar-content.stories.ts
  src/showcase/stories/angular/sidebar/sidebar-title/sidebar-title.stories.ts
  src/showcase/stories/angular/sidebar/sidebar/sidebar.stories.ts
  yarn.lock
Labels: pr: peer review required, pr: lead review approved
