Repository sbb-design-systems/lyne-angular, pull requests merged in 2025-05, with the labels that each got.

#95 feat: update lyne-elements to 2.9.0
  package.json
  tools/eslint/angular-generator-rule.ts
  tools/eslint/storybook-generator-rule.ts
  yarn.lock
Labels: pr: peer review approved

#94 fix: improve Angular Forms integration
  angular.json
  package.json
  src/angular-experimental/tsconfig.spec.json
  src/angular/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/angular/autocomplete/autocomplete.spec.ts
  src/angular/breadcrumb/breadcrumb-group/breadcrumb-group.spec.ts
  src/angular/checkbox/checkbox-panel/checkbox-panel.spec.ts
  src/angular/checkbox/checkbox/checkbox.spec.ts
  src/angular/chip/chip-group/chip-group.spec.ts
  src/angular/date-input/date-input.spec.ts
  src/angular/date-input/date-input.ts
  src/angular/datepicker/datepicker/datepicker.spec.ts
  src/angular/file-selector/file-selector/file-selector.spec.ts
  src/angular/form-field/form-field/form-field.spec.ts
  src/angular/notification/notification.spec.ts
  src/angular/notification/notification.ts
  src/angular/radio-button/radio-button-group/radio-button-group.spec.ts
  src/angular/select/select.spec.ts
  src/angular/slider/slider.spec.ts
  src/angular/table/table.spec.ts
  src/angular/tag/tag/tag.spec.ts
  src/angular/tag/tag/tag.ts
  src/angular/toggle-check/toggle-check.spec.ts
  src/angular/toggle/toggle/toggle.spec.ts
  src/angular/toggle/toggle/toggle.ts
  src/angular/tsconfig.spec.json
Labels: pr: peer review required, pr: lead review approved

#107 docs(sbb-table-wrapper): add table-usage doc
  src/showcase/stories/angular/table/table-wrapper/readme.md
  src/showcase/stories/angular/table/table-wrapper/table-wrapper.stories.ts
Labels: pr: peer review required, pr: lead review approved

#114 build: add workflow to automatically assign issues to Lyne's board
  .github/workflows/add-issues-to-project.yml
Labels: pr: peer review required, pr: lead review approved

#115 build: replace actions
  .github/workflows/release-please.yml
Labels: pr: peer review required
