Repository sbb-design-systems/lyne-angular, pull requests merged in 2025-04, with the labels that each got.

#53 feat: update to lyne-elements 2.6.0
  package.json
  src/angular/autocomplete-grid/autocomplete-grid/autocomplete-grid.ts
  src/angular/autocomplete/autocomplete.ts
  src/angular/chip/chip-group/chip-group.ts
  src/angular/chip/chip-group/index.ts
  src/angular/chip/chip-group/ng-package.json
  src/angular/chip/chip/chip.ts
  src/angular/chip/chip/index.ts
  src/angular/chip/chip/ng-package.json
  src/showcase/stories/angular/chip/chip-group/chip-group.stories.ts
  src/showcase/stories/angular/chip/chip/chip.stories.ts
  yarn.lock
Labels: pr: peer review required

#70 feat: update to lyne-elements 2.7.0
  eslint.config.js
  package.json
  src/angular/alert/alert-group/alert-group.ts
  src/angular/alert/alert/alert.ts
  src/angular/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.ts
  src/angular/autocomplete-grid/autocomplete-grid/autocomplete-grid.ts
  src/angular/autocomplete/autocomplete.ts
  src/angular/calendar/calendar.ts
  src/angular/checkbox/checkbox-panel/checkbox-panel.ts
  src/angular/checkbox/checkbox/checkbox.ts
  src/angular/chip/chip-group/chip-group.ts
  src/angular/container/sticky-bar/sticky-bar.ts
  src/angular/date-input/date-input.ts
  src/angular/datepicker/datepicker/datepicker.ts
  src/angular/dialog/dialog-title/dialog-title.ts
  src/angular/dialog/dialog/dialog.ts
  src/angular/expansion-panel/expansion-panel-header/expansion-panel-header.ts
  src/angular/expansion-panel/expansion-panel/expansion-panel.ts
  src/angular/file-selector/file-selector-dropzone/file-selector-dropzone.ts
  src/angular/file-selector/file-selector/file-selector.ts
  src/angular/flip-card/flip-card/flip-card.ts
  src/angular/image/image.ts
  src/angular/menu/menu/menu.ts
  src/angular/navigation/navigation/navigation.ts
  src/angular/notification/notification.ts
  src/angular/option/option/option.ts
  src/angular/overlay/overlay.ts
  src/angular/paginator/compact-paginator/compact-paginator.ts
  src/angular/paginator/paginator/paginator.ts
  src/angular/popover/popover/popover.ts
  src/angular/radio-button/radio-button-group/radio-button-group.ts
  src/angular/radio-button/radio-button-panel/radio-button-panel.ts
  src/angular/radio-button/radio-button/radio-button.ts
  src/angular/select/select.ts
  src/angular/selection-expansion-panel/selection-expansion-panel.ts
  src/angular/sidebar/sidebar/sidebar.ts
  src/angular/slider/slider.ts
  src/angular/stepper/step/step.ts
  src/angular/tabs/tab-group/tab-group.ts
  src/angular/tag/tag/tag.ts
  src/angular/time-input/time-input.ts
  src/angular/toast/toast.ts
  src/angular/toggle-check/toggle-check.ts
  src/angular/toggle/toggle/toggle.ts
  tools/eslint/angular-generator-rule.ts
  tools/eslint/storybook-generator-rule.ts
  yarn.lock
Labels: pr: peer review required, pr: lead review approved

#85 fix(sort): fix offset of focus-outline
  src/angular/table/sort/sort-header.scss
Labels: pr: peer review approved

#88 fix: fix output event types
  src/angular/alert/alert-group/alert-group.ts
  src/angular/alert/alert/alert.ts
  src/angular/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.ts
  src/angular/autocomplete-grid/autocomplete-grid/autocomplete-grid.ts
  src/angular/autocomplete/autocomplete.ts
  src/angular/calendar/calendar.ts
  src/angular/chip/chip-group/chip-group.ts
  src/angular/container/sticky-bar/sticky-bar.ts
  src/angular/datepicker/datepicker/datepicker.ts
  src/angular/dialog/dialog-title/dialog-title.ts
  src/angular/dialog/dialog/dialog.ts
  src/angular/expansion-panel/expansion-panel-header/expansion-panel-header.ts
  src/angular/expansion-panel/expansion-panel/expansion-panel.ts
  src/angular/file-selector/file-selector-dropzone/file-selector-dropzone.ts
  src/angular/file-selector/file-selector/file-selector.ts
  src/angular/flip-card/flip-card/flip-card.ts
  src/angular/menu/menu/menu.ts
  src/angular/navigation/navigation/navigation.ts
  src/angular/notification/notification.ts
  src/angular/option/option/option.ts
  src/angular/overlay/overlay.ts
  src/angular/paginator/compact-paginator/compact-paginator.ts
  src/angular/paginator/paginator/paginator.ts
  src/angular/popover/popover/popover.ts
  src/angular/radio-button/radio-button-group/radio-button-group.ts
  src/angular/select/select.ts
  src/angular/selection-expansion-panel/selection-expansion-panel.ts
  src/angular/sidebar/sidebar/sidebar.ts
  src/angular/slider/slider.ts
  src/angular/stepper/step/step.ts
  src/angular/table/table/table-data-source.ts
  src/angular/tabs/tab-group/tab-group.ts
  src/angular/tag/tag/tag.ts
  src/angular/time-input/time-input.ts
  src/angular/toast/toast.ts
  src/angular/toggle/toggle/toggle.ts
  tools/eslint/angular-generator-rule.ts
Labels: pr: peer review approved

#90 feat: lyne update 2.8.0
  package.json
  src/angular/paginator/compact-paginator/compact-paginator.ts
  src/angular/paginator/paginator/paginator.ts
  src/angular/table/table-wrapper/table-wrapper.ts
  yarn.lock
Labels: pr: peer review required

#89 build: setup unit tests
  .github/workflows/continuous-integration.yml
  angular.json
  package.json
  src/angular-experimental/karma.conf.js
  src/angular-experimental/timetable-row/timetable-row.spec.ts
  src/angular/karma.conf.js
  src/angular/table/table.spec.ts
  src/angular/table/table/table.ts
  tsconfig.spec.json
  yarn.lock
Labels: pr: peer review required, pr: lead review approved

#91 docs: fix readme reference to 'lyne-elements'
  README.md
Labels: pr: peer review required, pr: lead review approved
